<?php
$incrementId = $this->getOrderId();
if ($incrementId) {

	$order = Mage::getModel('sales/order')->loadByIncrementId($incrementId);

	if ($order->getPayment()->getMethodInstance()->getCode() == Trezo_BoletoFacil_Model_BoletofacilMethod::PAYMENT_METHOD_BANKTRANSFER_CODE) {
        echo "<h1>Boleto Fácil</h1>";
		try
		{
            $boleto = Mage::getModel('boletofacil/boleto')->generate($order);

            if ($boleto->getId()) {
                echo "<a href=\"{$boleto->getUrl()}\" target=\"_blank\">Imprimir Boleto</a>";
            }
            else {
                echo "<b>Não foi possível gerar o Boleto<br>"
                    . "Favor contate o administrador do site</b>";
            }
		}
		catch (Exception $e) {
            echo "<b>Não foi possível gerar o Boleto<br>";
			echo $e->getMessage();
		}
	}
}
?>